version: "3.9"

services:
  
  curriculm:
    platform: linux/amd64
    image: curriculum:latest
    container_name: curriculum
    build: 
      dockerfile: ci/Dockerfile
      context: .
    ports:
      - "80:80" 
    volumes:
      - .:/curriculum
    entrypoint: sh -c "npm i && npm run dev -- --port 80 --host"
